POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Novo evento",
  "details": "null",
  "maximumAttendees": 1
}

###

POST http://localhost:3333/events/2a0e3024-efab-4d71-be56-8221bdce24b1/attendees
Content-Type: application/json

{
  "name": "Pedro Henrique",
  "email": "pedrohenrique.teste@gmail.com"
}

###

GET http://localhost:3333/events/2a0e3024-efab-4d71-be56-8221bdce24b1

###

GET http://localhost:3333/attendees/1/badge

###

GET http://localhost:3333/attendees/1/check-in

###

GET http://localhost:3333/events/2a0e3024-efab-4d71-be56-8221bdce24b1/attendees